[package]
name = "liebe"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
mlua = { version = "0.10.3", features = ["anyhow", "luajit", "serialize"] }
serde = { version = "1.0.219", features = ["derive"] }
