[package]
name = "lcore"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
clap = "4.5.38"
mlua.workspace = true
lua_export = { path = "../lua_export/lua_export" }
toml = "0.8.22"
